plugins {
    id 'com.android.application'
}

android {
    compileSdk 33

    defaultConfig {
        applicationId "ru.zagonka.tv.wrapper"
        minSdk 23
        targetSdk 33
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
}

dependencies {
    implementation project(':input-core')
    implementation project(':web-input')
    testImplementation 'junit:junit:4.13.2'
}
